#!/bin/bash
set -e

# This script generates the matched_M_*.txt and matched_fs.txt files required
# by create_plots.sh. It does NOT produce matched.xlsx, report.txt, or
# matched.txt — those are generated by the main match.py call in pipeline.sh
# (line 14). If you need matched.xlsx or report.txt, run pipeline.sh first,
# or run the following command before this script:
#
#   python3 scripts/match.py -j jms/data/jms.json -u jms/data/45409.txt \
#     -m 1964/data/parsed/mg1964.txt -o matched.xlsx -g -v -l -r report.txt \
#     -M 0 -F -Y -P -n -e -a -s -d -O matched.txt
#
# Similarly, the match.py calls below do not produce .xlsx outputs. If you
# need an .xlsx file for a specific run, add -o <path>.xlsx to that call.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

JMS_INPUT_PATH="${SCRIPT_DIR}/../jms/data/jms.json"
JMS_LINKS_PATH="${SCRIPT_DIR}/../jms/data/45409.txt"
MG1964_INPUT_PATH="${SCRIPT_DIR}/../1964/data/parsed/mg1964.txt"

# Exact matching with M=0..5
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_0.txt -M 0 -F -Y -P -n -e -a -s -d -O matched_M_0.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_1.txt -M 1 -F -Y -P -n -e -a -s -d -O matched_M_1.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_2.txt -M 2 -F -Y -P -n -e -a -s -d -O matched_M_2.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_3.txt -M 3 -F -Y -P -n -e -a -s -d -O matched_M_3.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_4.txt -M 4 -F -Y -P -n -e -a -s -d -O matched_M_4.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_5.txt -M 5 -F -Y -P -n -e -a -s -d -O matched_M_5.txt

# Levenshtein distance <= 1, M=0..5
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_0_b_2_ld_1_ff.txt -M 0 -F -Y -P -n -e -a -s -d --ld -b 2 -t 1 --ff -O matched_M_0_b_2_ld_1_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_1_b_2_ld_1_ff.txt -M 1 -F -Y -P -n -e -a -s -d --ld -b 2 -t 1 --ff -O matched_M_1_b_2_ld_1_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_2_b_2_ld_1_ff.txt -M 2 -F -Y -P -n -e -a -s -d --ld -b 2 -t 1 --ff -O matched_M_2_b_2_ld_1_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_3_b_2_ld_1_ff.txt -M 3 -F -Y -P -n -e -a -s -d --ld -b 2 -t 1 --ff -O matched_M_3_b_2_ld_1_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_4_b_2_ld_1_ff.txt -M 4 -F -Y -P -n -e -a -s -d --ld -b 2 -t 1 --ff -O matched_M_4_b_2_ld_1_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_5_b_2_ld_1_ff.txt -M 5 -F -Y -P -n -e -a -s -d --ld -b 2 -t 1 --ff -O matched_M_5_b_2_ld_1_ff.txt

# Levenshtein distance <= 2, M=0..5
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_0_b_2_ld_2_ff.txt -M 0 -F -Y -P -n -e -a -s -d --ld -b 2 -t 2 --ff -O matched_M_0_b_2_ld_2_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_1_b_2_ld_2_ff.txt -M 1 -F -Y -P -n -e -a -s -d --ld -b 2 -t 2 --ff -O matched_M_1_b_2_ld_2_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_2_b_2_ld_2_ff.txt -M 2 -F -Y -P -n -e -a -s -d --ld -b 2 -t 2 --ff -O matched_M_2_b_2_ld_2_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_3_b_2_ld_2_ff.txt -M 3 -F -Y -P -n -e -a -s -d --ld -b 2 -t 2 --ff -O matched_M_3_b_2_ld_2_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_4_b_2_ld_2_ff.txt -M 4 -F -Y -P -n -e -a -s -d --ld -b 2 -t 2 --ff -O matched_M_4_b_2_ld_2_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_5_b_2_ld_2_ff.txt -M 5 -F -Y -P -n -e -a -s -d --ld -b 2 -t 2 --ff -O matched_M_5_b_2_ld_2_ff.txt

# Levenshtein distance <= 3, M=0..5
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_0_b_2_ld_3_ff.txt -M 0 -F -Y -P -n -e -a -s -d --ld -b 2 -t 3 --ff -O matched_M_0_b_2_ld_3_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_1_b_2_ld_3_ff.txt -M 1 -F -Y -P -n -e -a -s -d --ld -b 2 -t 3 --ff -O matched_M_1_b_2_ld_3_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_2_b_2_ld_3_ff.txt -M 2 -F -Y -P -n -e -a -s -d --ld -b 2 -t 3 --ff -O matched_M_2_b_2_ld_3_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_3_b_2_ld_3_ff.txt -M 3 -F -Y -P -n -e -a -s -d --ld -b 2 -t 3 --ff -O matched_M_3_b_2_ld_3_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_4_b_2_ld_3_ff.txt -M 4 -F -Y -P -n -e -a -s -d --ld -b 2 -t 3 --ff -O matched_M_4_b_2_ld_3_ff.txt
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_M_5_b_2_ld_3_ff.txt -M 5 -F -Y -P -n -e -a -s -d --ld -b 2 -t 3 --ff -O matched_M_5_b_2_ld_3_ff.txt

# Fellegi-Sunter matching
python3 "${SCRIPT_DIR}/match.py" -j "${JMS_INPUT_PATH}" -u "${JMS_LINKS_PATH}" -m "${MG1964_INPUT_PATH}" -g -v -l -r report_fs.txt -M 0 -F -Y -P -n -s -d --ld -b 3 --ff --fs --score --fs-review review.tsv -O matched_fs.txt
